config/routes.rb
Rails.application.routes.draw do
	resources :cats do
		resources :posts
	end

#	get '/cats/:id/upvote', to: 'cats#upvote'
#	get '/cats/:id/downvote', to: 'cats#downvote'
end

app/models/cat.rb
class Cat < ActiveRecord::Base
	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :cat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
		@cats = Cat.all
		flash[:notice] = "You were on the Cats index page last."
  end

  def edit
  end

  def show
  end

  def update
  end

  def create
  end

  def destroy
  end

  def new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
		@cat = Cat.find(params[:cat_id])
		@posts = @cat.posts
  end

  def create
		Post.new(cat_id: params[:cat_id])
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/cats/create.html.erb
<h1>Cats#create</h1>
<p>Find me in app/views/cats/create.html.erb</p>

app/views/cats/destroy.html.erb
<h1>Cats#destroy</h1>
<p>Find me in app/views/cats/destroy.html.erb</p>

app/views/cats/edit.html.erb
<h1>Cats#edit</h1>
<p>Find me in app/views/cats/edit.html.erb</p>

app/views/cats/index.html.erb
<h1>Cats#index</h1>
<p>Find me in app/views/cats/index.html.erb</p>
<hr>
<% @cats.each do |cat| %>
	<%= link_to cat.name, cat_path(cat.id) %>
	<%= link_to "DESTROY THE KITTY", cat_path(cat.id), method: :delete %><br>
<% end %>

app/views/cats/new.html.erb
<h1>Cats#new</h1>
<p>Find me in app/views/cats/new.html.erb</p>

app/views/cats/show.html.erb
<%= image_tag "http://placekitten.com/g/200/300" %>

<% if flash[:notice] %>
	<h4><%= flash[:notice] %>
<% end %>

app/views/cats/update.html.erb
<h1>Cats#update</h1>
<p>Find me in app/views/cats/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tinderforcats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>